sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-138
env:
  global:
    -
      # LTD_AWS_ID
      secure: v9X4HAYDGJxr25Q/pXM/luSPS481LHQzPbMK06FVrSRUWbpzCw1+7PiqmWUmy5f+ggOb6vwwymGImXeFjkkLGMYUBoNache0PhsayczWPyQZENtBCVhpgyJabaJO+ngRPSWXyeXWLhKoYfjjKe4lB8PvBJx0O0CwWQIQrEYAYNb0uX4puwfvDYgbAlcDg0axL9e3ytODGqaurwiE/hFJiYV0yV2Ql0Fpj61psZPdyScQ31UaJLM6ImL4batZ37yxuvfgxcLAmwPVeDd6eWfd8OGxkNfC49ZBMAObo+1LAgV/EI0zPg0JtDUiCT7D/cyYni0ulr+zUs+ruRT493UuX/1GPu9yMOERhiF8LMP75f40glBEj8QSe2iC0J4AWBj4KI6NjdNYMbyM2Be+kWdgHy9rQLc/Vb8myNeuxmUCOGRZ0TxMMgiI6ew4s+NWQJvvK9FMHRPe6bm9ybZjVEKbW8DUeyMXk0AaHp33PzCDmUs1bLgo3D8peJaTzF1mQae7TbA57fxPVScXxGITP4pXziGRUlsu0oRrFhItvlQXmrRyn3kFtXemfOKo3D3fzX/svcjflwuYAwv9+ae8EK0SyuAU9IOwyGxY8Hbi+0mm8VrsN2eEVYNAhYrwJOoOWxf55xU7auFNDe3who6rSATj9NgBbdAhzMTJuL3kETEVtWw=
    -
      # LTD_AWS_SECRET
      secure: E/Apcg3oTd+lHcwGMUpr5UcKlzuW7RW341zCzAKYiQRWynd1DX0q/ulM7TghFN2W74M10jGX1qU/N7oBz15nqa8kvTqyY61WZL8xMKdX/0zNZgoQrvuzRJiyXaD818hva6hdN7Y1h3O/Lb1N2n56e13fsJZ5Di60/u7cmaBUiKzzTKStjnJQhxlWdEjwHqcG0Rob0OKltga3qAYzVOl8GP06uAsIPij6T6amny8/e2k4NPHata06i+UrkN0e7+dZO8v8tfgsH2Jm+G5CCOz7pcfXM1yJUFCKHSfdZT5SfI10kR+Hrxk7GtDghvarrCWia8fYaHQ++29hLGhdu8DOv8tLu7n3D0xctTbVWyFoFVj/j3K8bCajl9s38Da8Xs/jDqdUypyhG2GNGy8QTYDqwkJx/hAQ2S59jwAuVDhDttd70QM+7ShcDova2fL2lV/Bt5SJl+Uo/I6yy/5dmhX9J7NSAzAYsRu9yzS5xEV9yXCm4A11SdA6whvSWDLsDSK8YTL9vnAtrBhP8K6umtiapU6nOOLdv3+RHjhT9wMYxDUvlVzkMABLlylQXJVH959urTq5IYwqRk7fKRgTUP7UeAzEpwOFr5UuH4oEPi+CsJLAUTMubWFrdvMHgrVT7ZL3VVqA4wSqQxehtrU56GVvPzhIGOHB6BrCT6TU7TntPhg=
    -
      # LTD_USERNAME
      secure: VvpOSGL4a+9ZKUT3/EMLx/qTofuuFSH8kcy9wcLdbZe5+LYgnT74kUtX+eChkRfgMaTbhVL2n3f8PVsHh5QTzwGzR31PRQfljuzdeSQXL9ZHUaz6qIZOVWz50J7YEgXelFjfaVkjQUBJ6c3VG+UZn9n8AUT/hZpzCEbf0pfgTx+hkTZzOtewk4mLFb2TiIelz0Y7DGctculnHhdD4MmjWw6wiZLg2F7MpjnShaj6h6vpsNBaRu7mb5BmO3jRnOtDdHUGrzvv82n0j0cHyLkWvjOkGjs9VHSyDPs2kYUi9EesqPz6Jq08enrszZPBmpt1M36UZtK22s+q0JhDJQZkvQvxdAw/BhLcbZmtzhEgQStPrRF25h1/KWDNXi4/GbYE4BTOMuaaS7hbicE8Jf/GOnap8eZuxMnE3pRJQYm3moIvsAt9ULSUhZ2fL7rpmR5iY2nNBUhpw39ImDRVB42sjvbatShKy85GEJO+yKY7su2jXqG+N74AyoxZEDgI9izAbNKk7tg5bi3Hmo7+Awr1KK9QaaP8Ke+e+d3GlsjeF2mKWTMcmWJToKFHysOaMaMjLvbWf99sGmFx98xD6iB51jtxCYDoj4WJF8a84lkXWDDg4QLLbQS2KTdcv+6EZ8QEzgPD0UN2dzqi0hiS8jZuC5+jwXAHkyqLmZ+eNdKJ2Jc=
    -
      # LTD_PASSWORD
      secure: QBbIb27a44mfftNEW0uaRbRN5uKp7rkNWBndjdRb1q8u5LGZ+iE/tljeMvt5RDeIM+YZ6Ot5HkZY/iSWAg/LEVZoxE3KGOccw5Yn3rebyY/tCz6Ka4A1TZpZUzSL3BiJ2+Gnp2N2JmflXUXFRfeYE3A88ki8f/Zwaxy8wBCqCxf5/CpIMjnX5Nf2GVYfA8n/9OvkhSikdxAVELHoWOJXOvsXR2Uf2HfUkDvf/GZuSRaWF5LSjjbWWwQBI1ZLuVYu+NWl2cUf+DvhczOosxipOSs9iVVo2KwHdPR3YswnKPRt3tg71LnYn004Wr8/kVRiiCdRYIUayfCBXwYrLF9SyH7KbrbhTxbPhlyB+iiae6ooVQhagjzqNa348J1SgGOo0sGU1Qug9XP1QvwE/5KFjVmEW3MQGzhzz3ePWcz1z0wCEnWlWwl1ml9SNyNl7D6LKG4IZv+RDj1pp9KOgZS8zNbOEuZbpQZBBGM+MwXlNuurs27WPu0JXPuq9Klgv0+T5HSrT8fc42XXkbtBoniSnYEt8vw4RpHrD/Sj7ZgRzHlqZZzMq2CMpT7yqhdVojIB17sZs6q6oBCcRM27N3kprdN1OHE6kJx6ARo+kEaOUELW2xKCFT+HK9gWiATubZc3p3jUDEerpqcn122lV5NAw/88BZt1TWmwMmEY99MI2zo=
